### ISSUE TITLE
NPM start in `test` results in webpack failure

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-vue-pdf417#17]
This is with a fresh install using commit f7357aa048e9e8cad27207b5edf3894e61f1a0e5

https://gist.github.com/mattcollier/379d6741eb0e1cfeb5a19b628ee929ab

**Comment by mattcollier** [comment]
Pinning to `bedrock@4.4.3` allows the webpack build to complete successfully.

https://github.com/digitalbazaar/bedrock/compare/v4.4.3...main

**Comment by dlongley** [comment]
Test suite deps were very old -- some even running on old branches. Updated and test suite runs now -- though it has no tests.
